version: 2.1
jobs:
  build:
    docker:
     - image: circleci/node:lts
    working_directory: ~/src
    steps:
      - checkout:
            path: ~/
      - run: npm ci
      - run: npm run test

workflows:
  build_and_test:
    jobs:
      - build